#+Title: Projeto do Curso ED 2016.2 

* Introdução

/Demo/ http://fgv-goal.mybluemix.net
   
Um padrão para montagem de arquivos foi estabelicido para auxiliar a
manutenção de um baco de questões colaborativo inspirado no [[http://www.newgradiance.com/downloads/auth-guide.pdf][GOAL -
Gradiance On-Line Accelerated Learning]]

O XML é uma linguagem de marcação flexível usados para atribuir
explicitamente significado ou formatação a arquivos de texto. Mais
informações podem ser encontradas nas seguintes fontes:

- w3school http://www.w3schools.com/xml/xml_whatis.asp
- outro site com tutoriais http://www.xmlfiles.com/xml
 
As tags e seus respectivos atributos, que usaremos na produção das
questões, futuramente definidas em um Xml Schema são:
 
- question :: tag raiz do documento.

  - level :: inteiro de 1 a 3, indicando em de forma crescente a
    dificuldade da questão.
	
  - chapter :: número indicando o capítulo de referência do livro texto.
    
  - id :: indetificador único para a questão.
	
- text :: uma área de texto, que pode estar no enunciado ou no corpo de
  uma opção.
 
  - choice :: opção da questão.
 
  - type :: string (correct ou incorrect), indicando se a opção está
    correta ou não.
		
- explanation :: explicação para uma determinada opção estar correta ou
  falsa.
 
- tags html :: qualquer tag html pode ser utilizada para formatação do
     texto.
  
* Recomendações

Um esquema será futuramente definido para validações dos arquivos xml,
a fim de que as recomendações abaixo sejam atendidas.

- As tags text explanation e option, devem ser filhas de question.
 
- As tags html podem se localizar em qualquer lugar do arquivo.
 
- Devem haver ao menos 5 opções, pelo menos 4 opções incorretas e pelo
  menos 1 correta.
 
- O atributo correct de option é obrigatório e deve se restringir aos
  valores 'correct' e 'incorrect'.
 
- Para a criação das questões e respostas deve seguir as sugestões do
  GOAL.
 
- Os sites utilizados como referência devem estar nessa lista::

  - https://www.wikipedia.org/
  
  - https://www.quora.com/
  
  - http://cs.stackexchange.com/
  
  - http://math.stackexchange.com/
  
  - http://stackoverflow.com/

* Validação

#+BEGIN_SRC bash
xmllint --valid template-1.xml
#+END_SRC

O template-2.xml terá ainda erros de validação. E o que falta é dizer
que todas as tags de XHTML válida dentro de uma tag p devem ser
válidas para <text> e <explanation>. Também falta declarar
corretamente os atributos que recebem URIs.

* Desenvolvimento

Para colaboração com o repositório, deve-se consultar as Issues do repositório de desenvolvimento https://github.com/eduardocesar93/FGV-Goal. Abaixo segue um passo a passo para executar o sistema localmente. 

- Possui interpretador Python https://www.python.org/ e um editor de texto.

- Recomenda-se estudar a documentação do Flask http://flask.pocoo.org/, que é a microframework utilizada junto ao python.

- Os pacotes python utilizados utilizados devem ser adicionados ao arquivo 'requirements.txt', caso não possua alguns dos pacotes instalados pode-se instalá-lo a partir do comando:
#+BEGIN_SRC bash
pip install nomedopacote
#+END_SRC

- Para executar o sistema localmente, deve-se no diretório do projeto executar o comando:
#+BEGIN_SRC bash
python app.py
#+END_SRC

- A página inicial do sistema estará disponível em http://localhost:8080 e pode ser acessada a partir de qualquer navegador.
